### PR TITLE
Adding a clock from the server

### PR DESCRIPTION
**Pull request by gbrault**
I just added few lines of codes in the server.py and add a span in the index.html.

Of course it's a bit bigger than the original, but still simple enough to grasp the concept.

It shows the ws can really be a two way channel

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Thanks. Unfortunately I cannot accept this change due to a few problems:

- The `echo.py` is supposed to be a simple example that allows a client and a server to communicate. It does not make sense to add a clock to an "echo" example.
- A clock is not a great example use case for WebSocket, because the client is perfectly able to run a clock without server assistance.
- The way you have implemented threads is suboptimal. Each client gets its own thread, but all these threads are returning the same thing. A better design would be to have a single background thread that emits to all clients.

**Comment by gbrault** [comment]
No issue @miguelgrinberg I understand the points. My purpose was to provide an example of ws communication which was unattended from the client perspective.

**Comment by miguelgrinberg** [comment]
@gbrault Yes, and I am okay with the idea of adding a separate example that shows how to send from server to client. Mixing this with the echo example makes the code more difficult to understand.

**Comment by gbrault** [comment]
Totally agree! Do you want me to make a proposal? (and an according modified pull-request)?

**Comment by miguelgrinberg** [comment]
Yes, feel free to submit a new PR with a separate example. Thank you!

**Pull request closed without merging**
